### ISSUE TITLE
Error while running npm install

### ISSUE THREAD

**Issue by daksh0225** [scorelab/dengue-stop#125]
Receiving the following error on running ```npm install```
```
> react-native-router-flux@4.0.0-beta.7 postinstall /home/daksh0225/open-source/dengue-stop/node_modules/react-native-router-flux
> opencollective postinstall

/home/daksh0225/open-source/dengue-stop/node_modules/core-js/modules/_typed-buffer.js:157
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
                                ^

RangeError: Wrong length!
    at validateArrayBufferArguments (/home/daksh0225/open-source/dengue-stop/node_modules/core-js/modules/_typed-buffer.js:157:39)
    at new ArrayBuffer (/home/daksh0225/open-source/dengue-stop/node_modules/core-js/modules/_typed-buffer.js:247:29)
    at zlib.js:334:28
    at NativeModule.compile (internal/bootstrap/loaders.js:300:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:217:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Function.Module._load (internal/modules/cjs/loader.js:685:15)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/daksh0225/open-source/dengue-stop/node_modules/opencollective/node_modules/node-fetch/index.js:12:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-router-flux@4.0.0-beta.7 postinstall: `opencollective postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-router-flux@4.0.0-beta.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daksh0225/.npm/_logs/2020-03-17T20_53_02_908Z-debug.log
```
Can't run the react-native app as a result. Getting the following errors:
![Screenshot_20200318_022513_com dengue_stop](https://user-images.githubusercontent.com/47697056/76900669-ce746c00-68bf-11ea-8b6c-d053d412a319.jpg)

![Screenshot_20200318_022506_com dengue_stop](https://user-images.githubusercontent.com/47697056/76900655-c9172180-68bf-11ea-80d5-e8d6d56a9b90.jpg)

**Comment by m1-key** [comment]
There are lot of building issues with this app. So it would be waste of time to build this. As one of the mentor said that they will fix this once the coding period starts.
